server:
  port: 8080

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/heycar-garage
    username: postgres
    password: postgres
    hikari:
      maximumPoolSize: 5
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml